name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.x'

      - name: Install Quarto
        run: |
          R -e "install.packages('quarto', repos='https://r-lib.github.io')"
          quarto::install_quarto()

      - name: Build website
        run: quarto render

