project:
  type: website

website:
  title: "project"
  navbar:
    left:
        text: Home
        file: index.qmd
      - about.qmd
      - eda.qmd
      - Model.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

