project:
  type: website

website:
  title: "project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
        text: About
      - href: eda.qmd
        text: Exploratory Data Analysis
      - href: Model.qmd
        text: Model

content:
  dir: content  # Specify the directory containing content files
  include:
    - Model.qmd
    - app.py
    - eda.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

